### ISSUE TITLE
Generamba generator: Could not find 'generamba'

### ISSUE THREAD

**Issue by vladimir-ionita** [rambler-digital-solutions/Generamba#103]
I'm trying to generate a module using:
`generamba gen Login rviper_controller`
and I'm getting this:

```
/Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /KMinute (Errno::EACCES)
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `each'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/generamba-0.7.4/lib/generamba/module_generator.rb:15:in `generate_module'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/generamba-0.7.4/lib/generamba/cli/gen_command.rb:66:in `gen'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/gems/generamba-0.7.4/bin/generamba:5:in `<top (required)>'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/generamba:23:in `load'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/generamba:23:in `<main>'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Using with sudo gives another error:

```
/Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'generamba' (>= 0.a) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/Vlad/.gem/ruby/2.3.0:/Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /Users/Vlad/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/generamba:22:in `<main>'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Vlad/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

What could this be?

**Comment by etolstoy** [comment]
Hi, @vlad-ionita! Thanks for reporting.

What version of ruby are you using?

**Comment by vladimir-ionita** [comment]
It seems that I updated to 2.3.0 before installing generamba

**Comment by mogol** [comment]
@vlad-ionita,
1. You have no write permission to selected folder. Check and fix it. 
2. You have RVM and generamba under your normal user Vlad, not su/sudo.  In that case you can install RVM/generamba under sudo. To my mind, it's quite strange,so fixing permission is better.

**Comment by vladimir-ionita** [comment]
@mogol,
Thank you for you help!

I installed generamba with sudo
`sudo gem install generamba`
and now it works, even if I do a generate command without sudo.

Very strange, I did not modify any permissions, but it works! Thank you!
