### ISSUE TITLE
Crashes for multiple project targets

### ISSUE THREAD

**Issue by mogol** [rambler-digital-solutions/Generamba#150]
Hey,

There are two targets in project. So, I have in Rambafile

``` yaml
# The main project target name
project_targets: Dev.Target,AppStore
```

When do 

``` bash
generamba gen MyAwesomeList template_name
```

I got

```
/Users/gsaprykin/.rvm/gems/ruby-head/gems/generamba-1.2.0/lib/generamba/helpers/gen_command_table_parameters_formatter.rb:10:in `prepare_parameters_for_displaying': undefined method `join' for "Dev.Target,AppStore":String (NoMethodError)
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/generamba-1.2.0/lib/generamba/cli/gen_command.rb:50:in `gen'
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/gsaprykin/.rvm/gems/ruby-head/gems/generamba-1.2.0/bin/generamba:5:in `<top (required)>'
    from /Users/gsaprykin/.rvm/gems/ruby-head/bin/generamba:22:in `load'
    from /Users/gsaprykin/.rvm/gems/ruby-head/bin/generamba:22:in `<main>'
    from /Users/gsaprykin/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
    from /Users/gsaprykin/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mogol** [comment]
There is a bug in docs. Should be

``` yaml
# The main project target name
project_targets: [Dev.Target,AppStore]
```
