### ISSUE TITLE
Error install multiple templates from a single repository

### ISSUE THREAD

**Issue by ismetanin** [rambler-digital-solutions/Generamba#153]
I'm trying to add custom templates from my repo to my Rambafile, but i see error:

```
Installing swift_viper_module...
/Users/Ivan/.rvm/gems/ruby-2.2.1/gems/git-1.2.9.1/lib/git/lib.rb:917:in 'command': git  clone '--' 'https://github.com/lvinoeserdce/generamba-modules/tree/master/swift_viper_module' '/var/folders/6d/8w095f7n0q92q5xp9nqld4cr0000gn/T/swift_viper_module'  2>&1:Cloning into '/var/folders/6d/8w095f7n0q92q5xp9nqld4cr0000gn/T/swift_viper_module'... (Git::GitExecuteError)
fatal: repository 'https://github.com/lvinoeserdce/generamba-modules/tree/master/swift_viper_module/' not found
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/git-1.2.9.1/lib/git/lib.rb:76:in 'clone'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/git-1.2.9.1/lib/git/base.rb:29:in 'clone'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/git-1.2.9.1/lib/git.rb:97:in 'clone'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/template/installer/remote_installer.rb:24:in 'install_template'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/template/processor/template_declaration.rb:32:in 'install'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/template/processor/template_processor.rb:42:in 'block in install_templates'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/template/processor/template_processor.rb:40:in 'each'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/template/processor/template_processor.rb:40:in 'install_templates'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/lib/generamba/cli/template/template_install_command.rb:18:in 'install'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in 'invoke'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in 'block in subcommand'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1@global/gems/generamba-1.2.0/bin/generamba:5:in '<top (required)>'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/bin/generamba:23:in 'load'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/bin/generamba:23:in '<main>'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in 'eval'
    from /Users/Ivan/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in '<main>'
```

My Templates section:

```
### Templates
templates:
- {name: swift_viper_module, git: 'https://github.com/lvinoeserdce/generamba-modules/tree/master/swift_viper_module'}
- {name: swift_service_module, git: 'https://github.com/lvinoeserdce/generamba-modules/tree/master/swift_service_module'}
```

My generamba-modules catalog: [https://github.com/lvinoeserdce/generamba-modules](url)

**Comment by etolstoy** [comment]
What version are you using?

**Comment by ismetanin** [comment]
@etolstoy 1.2.0

```
MacBook-Air-Ivan:~ Ivan$ sudo gem which generamba
/Users/Ivan/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/generamba-1.2.0/lib/generamba.rb
```

**Comment by etolstoy** [comment]
@lvinoeserdce looks like a bug, thanks. We'll fix it soon.

**Comment by etolstoy** [comment]
Hi, @lvinoeserdce! Sorry for the long reply! I've checked your bug once more - it looks like you are using a template catalog wrong.

Use the following syntax:

``` yml
catalogs:
- 'https://github.com/lvinoeserdce/generamba-modules'

templates:
- {name: swift_viper_module}
- {name: swift_service_module}
```

Here is the [wiki](https://github.com/rambler-ios/Generamba/wiki/Rambafile-Structure#templates-settings) reference. Does it help you?

**Comment by ismetanin** [comment]
Hi, @etolstoy! You're right, it helped me. Your 'wiki referense' is outdated. But I've already fixed my bug with you help :)
Thank you!

**Comment by NikKovIos** [comment]
Hello, i have a same issue:
https://github.com/NikKovIos/generambaOpenTemplatesIOS

```
catalogs:
- 'https://github.com/NikKovIos/generambaOpenTemplatesIOS'

templates:
- {name: sml_viper, git: 'sml_viper'}
- {name: sml_viper_dip, git: 'sml_viper_dip'}
```

```
generamba template install
Installing sml_viper...
/Users/nikitakovalenok/.rvm/gems/ruby-2.2.4/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git  clone '--' 'sml_viper' '/var/folders/z2/y6t802gd33x0bf9cy2z_lws40000gr/T/sml_viper'  2>&1:fatal: repository 'sml_viper' does not exist (Git::GitExecuteError)
```

When there is a single .rambaspec in repo it installs properly. But when they are in multiple folders it is such an error.
