### ISSUE TITLE
Exception when using custom_name in a template

### ISSUE THREAD

**Issue by nalexn** [rambler-digital-solutions/Generamba#199]
I'm trying to create my own template and want to name files based on the module name, for example `MyModulePresenter.swift`

The key portion of my *.rambaspec file looks like this:
```swift
code_files:
- {custom_name: "{{ module_info.name }}Presenter.swift", path: Code/Presenter.swift.liquid}
```
When I run
```
$ generamba gen MyModule template_name
```
I get this output:
```
+----------------+--------------------------------------------+
|                   Summary for gen MyModule                   |
+----------------+--------------------------------------------+
blah blah blah
+----------------+--------------------------------------------+

Creating code files...
/usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/module_generator.rb:74:in `dirname': no implicit conversion of nil into String (TypeError)
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/module_generator.rb:74:in `block in process_files_if_needed'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/module_generator.rb:63:in `each'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/module_generator.rb:63:in `process_files_if_needed'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/module_generator.rb:22:in `generate_module'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/lib/generamba/cli/gen_command.rb:72:in `gen'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/generamba-1.4.1/bin/generamba:5:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.0/bin/generamba:23:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.0/bin/generamba:23:in `<main>'
```

**Comment by kei-sidorov** [comment]
I had same exception when I tryed to use custom_name. I fixed it localy, but my team cant use my templates. Please, make higher priority for this issue.

**Comment by tribushevsky** [comment]
Try to use the following code:
code_files:
- {name: "{{ module_info.name }}Presenter.swift", path: Code/Presenter.swift.liquid}
