### ISSUE TITLE
Xcode 10.0 support.

### ISSUE THREAD

**Issue by oleksandr-zarochintsev** [rambler-digital-solutions/Generamba#220]
When trying to use `generamba gen`, against the projects created using Xcode 10.0 - the following error occurs:

```
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/generamba-1.4.1/lib/generamba/helpers/xcodeproj_helper.rb:9:in `obtain_project'
	from /Library/Ruby/Gems/2.3.0/gems/generamba-1.4.1/lib/generamba/cli/gen_command.rb:60:in `gen'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/generamba-1.4.1/bin/generamba:5:in `<top (required)>'
	from /usr/local/bin/generamba:22:in `load'
	from /usr/local/bin/generamba:22:in `<main>'
```

I set Xcode project format to Xcode 8.0 - compatible, but this not working for me.

**Comment by oleksandr-zarochintsev** [comment]
I resolved this issues, this is XCode 10 problem, see [this](https://github.com/CocoaPods/CocoaPods/issues/7835).
