### ISSUE TITLE
Update please Generamba

### ISSUE THREAD

**Issue by ceprus** [rambler-digital-solutions/Generamba#221]
```
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/generamba-1.4.1/lib/generamba/cli/setup_command.rb:31:in `setup'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/generamba-1.4.1/bin/generamba:5:in `<top (required)>'
	from /usr/local/bin/generamba:22:in `load'
	from /usr/local/bin/generamba:22:in `<main>'

```

**Comment by Brain89** [comment]
See [Issue-220](https://github.com/rambler-digital-solutions/Generamba/issues/220)
