### ISSUE TITLE
Crash when setup on project with RxSwift

### ISSUE THREAD

**Issue by vitt0re** [rambler-digital-solutions/Generamba#224]
Hello
I've created project and installed RxSwift on it with cocoa pods

- XCode 10.0
**Following was changed:**
- Deployment Target: 9.0
- Swift version 4.0
- Project Document/Project format: XCode 8.0-compatible
- Always Embed Swift Standard Libraries: No

program build is OK
-----------------
Now when I do **generamba setup** it returns

> victors-mbp:BRWClient victormironchik$ generamba setup
The company name which will be used in the headers: IBA
The name of your project is BRWClient. Do you want to use it? (yes/no) y
The project prefix (if any): 
The path to a .xcodeproj file of the project is 'BRWClient.xcodeproj'. Do you want to use it? (yes/no) y
/Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:321:in 'configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in 'new_from_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in 'object_with_uuid'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in 'block (2 levels) in configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in 'each'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in 'block in configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in 'each'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in 'configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in 'new_from_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in 'object_with_uuid'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in 'block (2 levels) in configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in 'each'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in 'block in configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in 'each'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in 'configure_with_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in 'new_from_plist'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:202:in 'initialize_from_file'
	from /Users/victormironchik/Software/ruby/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in 'open'
	from /Users/victormironchik/Software/ruby/gems/generamba-1.4.1/lib/generamba/cli/setup_command.rb:31:in 'setup'
	from /Users/victormironchik/Software/ruby/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /Users/victormironchik/Software/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Users/victormironchik/Software/ruby/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /Users/victormironchik/Software/ruby/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Users/victormironchik/Software/ruby/gems/generamba-1.4.1/bin/generamba:5:in '<top (required)>'
	from /Users/victormironchik/Software/ruby/bin/generamba:22:in 'load'
	from /Users/victormironchik/Software/ruby/bin/generamba:22:in '<main>'

Could you please help to fix it?
PS. I'm using workspace to build (cocoa pods requirement) Is it problem?
Thanks
Victor

**Comment by Incorporalis** [comment]
duplicates #225 
resolved by #222
