### ISSUE TITLE
Default template set can not be used

### ISSUE THREAD

**Issue by appleios** [rambler-digital-solutions/Generamba#60]
My ruby is version `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`. 

I've installed the gem with `gem install generamba`. Then as described [here](http://www.youtube.com/watch?v=NXNiN9FaUnY) I did `generamba setup` and after answering several questions, I've got the `Rambafile`.

When I tried `generamba template install` I've got this error message:

```
/Users/xxx/.rvm/gems/ruby-2.2.2/gems/generamba-0.7.1/lib/generamba/template/processor/template_processor.rb:21:in `install_templates': undefined method `map' for nil:NilClass (NoMethodError)
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/generamba-0.7.1/lib/generamba/cli/template/template_install_command.rb:14:in `install'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/gems/generamba-0.7.1/bin/generamba:5:in `<top (required)>'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/bin/generamba:23:in `load'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/bin/generamba:23:in `<main>'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/xxx/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

Actually the error means that there are no templates, and in Rambafile, there are:

```
### Templates
templates:
#- {name: local_template_name, local: 'absolute/file/path'}
#- {name: remote_template_name, git: 'https://github.com/igrekde/remote_template'}
#- {name: catalog_template_name}
```

Its ok, but shouldn't it say that there are no templates to install instead of throwing an error?

P.S. None of the provided templates can be used as is.

**Comment by etolstoy** [comment]
@appleios thanks for reporting! We'll add a more informative error message.

And the commented templates are not meant to be used in real applications - they are just mark-up examples.
