### ISSUE TITLE
Errors if default path is empty

### ISSUE THREAD

**Issue by MaximBazarov** [rambler-digital-solutions/Generamba#64]
if Rambafile contains: 

```
# The file path for new modules
project_file_path: 

# The Xcode group path to new modules
project_group_path: 
```

then we have this error

```
rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/lib/generamba/code_generation/code_module.rb:33:in `initialize': no implicit conversion of nil into String (TypeError)
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/lib/generamba/code_generation/code_module.rb:33:in `new'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/lib/generamba/code_generation/code_module.rb:33:in `initialize'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/lib/generamba/cli/gen_command.rb:40:in `new'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/lib/generamba/cli/gen_command.rb:40:in `gen'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/generamba-0.7.1/bin/generamba:5:in `<top (required)>'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/bin/generamba:23:in `load'
    from /Users/maksimbazarov/.rbenv/versions/2.2.3/bin/generamba:23:in `<main>'
```

May be it is ok, and should be, but would be great have error message instead

**Comment by etolstoy** [comment]
Thanks for reporting, that reminds me of another related issue. 

That's definitely a bug - I can imagine a template, which includes only tests. We'll fix it in the upcoming version.
