### ISSUE TITLE
Error on empty template folder

### ISSUE THREAD

**Issue by AndreyZarembo** [rambler-digital-solutions/Generamba#76]
Got error when run `generamba template install` with empty template folder. Traceback:

```
MAC275RDS:Mail a.zarembo$ generamba template install
/Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_declaration.rb:21:in `[]': no implicit conversion of String into Integer (TypeError)
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_declaration.rb:21:in `initialize'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_processor.rb:32:in `new'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_processor.rb:32:in `block in install_templates'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_processor.rb:31:in `each'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_processor.rb:31:in `map'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/template/processor/template_processor.rb:31:in `install_templates'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/lib/generamba/cli/template/template_install_command.rb:18:in `install'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/gems/generamba-0.7.2/bin/generamba:5:in `<top (required)>'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/bin/generamba:23:in `load'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/bin/generamba:23:in `<main>'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/a.zarembo/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by etolstoy** [comment]
@AndreyZarembo can you provide more information? What kind of template did you install - local, remote, or from catalog? Was the folder really empty, or did it contain a `rambaspec` file?

That's strange, because we already have a `rambaspec`-file existance verification logic.

**Comment by etolstoy** [comment]
Closing the issue as outdated.
